
development:
  adapter: postgresql
  encoding: utf8
  database: mobiledev_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: 
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST