# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017dd982f7b4f846fc438e4743a6e44586d84b983638689f3f1bb369a96a174f756b3778f98ff90ee7c5622c524e532555a9445926cabc16e862a417f209199f

test:
  secret_key_base: e04ab1acd6e46bc829403fe14d2bc60dd9745f87a462b071fa81e15ac1e094e741b0c9c55810463ee5208917f2724d60b83f2e1ca37de3fc968ca92840e4f94e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
